### PR TITLE
ajb,aubuf: timestamp is given in [us]

### PR DESCRIPTION
**Pull request by cspiel1**
- In ajb.c change the timestamp unit from RTP timestamps (sample count) to [us]
  per sample.
- In aubuf.c adjust the timestamp for an audio frame only if there is partial
  read.

### CODE REVIEW

**Comment by cspiel1** [comment]
Try to replace `re_printf()` for debug level 6 with `re_trace` API.

**Comment by cspiel1** [comment]
@sreimers It would be nice if the re_trace API had beside the JSON form a custom form format. For the ajb plot I want a CSV format with different kind of column types: string, pointer, uint and int.

Also most of the parameters are too much. Currently I need only the `arg_value`.

**Comment by sreimers** [comment]
> @sreimers It would be nice if the re_trace API had beside the JSON form a custom output format.

 I will take a closer look and think about something. Maybe you can convert the json output with `jq`

**Comment by sreimers** [comment]
Maybe you can use something like this (untested):

```c
re_trace_event("ajb", "plot", 'I', 0, 0, RE_TRACE_ARG_STRING_COPY, "csv", "1;2;3");
```

And with `jq` you can put the csv values into one file.

**Comment by cspiel1** [comment]
Yes, this is what I do for now.

**Pull request merged**
