### PR TITLE
make: bump version and set dev identifier

### PR DESCRIPTION
**Pull request by cspiel1**

### CODE REVIEW

**Comment by cspiel1** [comment]
In cmake we have no `PROJECT_VERSION_FULL`. And I am not sure if this is correct:
```
target_compile_definitions(rem-objs PRIVATE ${RE_DEFINITIONS})
```
Should it be `REM_DEFINITIONS` ?

Do we need something like in `re`:
```
list(APPEND RE_DEFINITIONS
  -DVERSION="${PROJECT_VERSION_FULL}"
  -DVER_MAJOR=${PROJECT_VERSION_MAJOR}
  -DVER_MINOR=${PROJECT_VERSION_MINOR}
  -DVER_PATCH=${PROJECT_VERSION_PATCH}
)
```

**Comment by cspiel1** [comment]
Should we also merge this, or complete the CMakeLists.txt with `dev` extension?

**Comment by cspiel1** [comment]
Should we close this for now? The "-dev" support in CMakeLists.txt is missing.

**Comment by sreimers** [comment]
Is added now: https://github.com/baresip/rem/pull/95

**Pull request closed without merging**
