### PR TITLE
aubuf insert auframes sorted

### PR DESCRIPTION
**Pull request by cspiel1**
Insert audio frames sorted by timestamps.

relates to: https://github.com/baresip/re/pull/209

### CODE REVIEW

**Comment by cspiel1** [comment]
The second commit (changing the API) could be avoided, if we want the timestamp to be interpreted as optional field for an audio frame. Should timestamp be mandatory or not? Thus changing `auframe_init()` or not?

**Comment by sreimers** [comment]
I think auframe_init() is a bit heavy (calls memset everytime). I prepared a PR https://github.com/baresip/rem/pull/19 to only update necessary fields (since srate, fmt and ch should not change).

For example currently a audio record handler looks like this:

```c
record_handler(...)
{
...
	auframe_init(&af, st->prm.fmt, sampv, sampc, st->prm.srate,st->prm.ch);

	af.timestamp = AUDIO_TIMEBASE*inStartTime->mSampleTime / st->prm.srate;
...
}
```

new api:

```c

record_alloc(...)
{
        auframe_init(st->af, fmt, sampv, sampc, ch);
}

record_handler(...)
{
	struct ausrc_st *st = userData;
...
	auframe_update(st->af, sampv, sampc, timestamp);
...
}
```

**Comment by cspiel1** [comment]
Ok, then we don't need the second commit. Removed it.

**Comment by cspiel1** [comment]
Just push updated retest. I don't have permissions to re-start the github actions.

**Comment by cspiel1** [comment]
Let me give the argument why this PR should be an improvement:

The idea is that inserting sorted is less expensive, than appending and then sorting the list each iteration.

**Comment by sreimers** [comment]
I will test the performance a bit, we can also improve with pre-allocating aubuf list entries (mbuf). My initial idea was to reorder only if needed (detected by RTP Packet out of order). But your solution is simpler (since we need no detection algorithm).

**Pull request merged**
